# Generated by Django 4.2.9 on 2026-02-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recieveActivities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Ramdan_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
