# Generated by Django 5.2.10 on 2026-02-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recieveActivities', '0003_activityparticipant_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
